- pyre/pyre_node.py
- pyre/pyre_peer.py
Headers now initially a dict instead of a list.
get_header returns "" instead of None
> fixed some issues with headers.

- pyre/pyre.py
- pyre/pyre_node.py
Another possibility is to use get_name with a peer id argument?
> suggested fix for #43 and https://github.com/zeromq/zyre/issues/297

- pyre/pyre.py
- pyre/pyre_node.py
- pyre/pyre_peer.py
- pyre/zbeacon.py
- pyre/zsocket.py
- tests/test_pyre.py
- tests/test_zbeacon.py
To reflect changes in Zyre and for better shutdown control
> Refactor of ZBeacon

- pyre/zbeacon.py
Implements Multicast support, and uses a default Multicast port when there is no suitable interface present.  
I tested this on OS X using `chat.py` with and without an internet connection.
> Add a fallback to multicast

- .travis.yml
- AUTHORS
- pyre/pyre_node.py
- pyre/zbeacon.py
- pyre/zhelper.py
- setup.py
- tests/test_pyre.py
- tests/test_stub.py
- Allow pip to install dependencies
- Fix support for Python 2
- Allow for a drop and return of connectivity
- Clean up Travis script
> Usability Enhancements

- examples/high_volume.py
```
$ python high_volume.py
Waiting for Peer...
WARNING:root:can't set ROUTER_HANDOVER, needs zmq version >=4.1 but installed is 4.0.4
Got 1000 msgs in 0.38 sec
FINISHED
```
> Add an advanced example showing a start up sync and high volume

- pyre/pyre.py
Otherwise the Pyre class can't be used in inherited situations
> fixed constructor and added super() method

- README.md
- examples/chat.py
- pyre/pyre_node.py
added JSON packed HEADERS to ENTER message and adjusted README and example/chat.py accordingly
fixes #78
> added JSON packed HEADERS to ENTER message

- examples/chat.py
Without these changes the example just doesn't work for me. Please review!
> Fixed formatting and missing decodes.

- examples/high_volume.py
get_peer_groups -> peer_groups
> Fixed method name

- pyre/pyre.py
- tests/test_pyre.py
> fix for a small bug, added shout bytes test

- docs/index.rst
- pyre/__init__.py
- pyre/pyre_event.py
Solution: Implement PyreEvent
See #92. Tested but might need own test class. Also, documentation has to be re-generated. I do not know how to do that.
> Problem: Pyre does not implement zyre_event

- pyre/pyre_peer.py
Prefix DEALER identity with chr(1) instead of b’1’
Fixes #97
> Problem: Wrong UUID prefix

- pyre/pyre.py
- pyre/pyre_node.py
Solution: Implement `peer_headers`
> Problem: No method to access all headers of a peer

- pyre/pyre.py
Solution: Use current API for chat_task
> Problem: chat_task is outdated.

- pyre/pyre.py
- pyre/pyre_node.py
- tests/test_pyre.py
Solution: Implement such a method as suggested by
https://github.com/zeromq/pyre/issues/102#issuecomment-258093666
Fixes #102
> Problem: peers_by_group not implemented

- pyre/pyre_node.py
- pyre/zre_msg.py
- setup.py
Detailed problems:
- The shouting side only sends the first frame of the multipart shout
- The receiving part drops all content frames but the first
Fix: Remove these restrictions.
> Problem: Receiving multipart shouts and whispers does not work

- examples/chat.py
- pyre/pyre.py
https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection
> Define raw_input() for Python 3

- pyre/zhelper.py
https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection  This approach will work with Python 4 ;-)
> try: u = unicode

- pyre/zsocket.py
It creates problem changing zmq import to zmq.green import
> Fix constructor issue

- .travis.yml
- pyre/pyre.py
Fixes #126
Adds 3.7 as travis testing target
> Fix PEP 479/Python 3.7 incompatibility

- pyre/zhelper.py
Hello,
This follows my discussion with @sphaero.
It would be cool for this project to be re-licensed under MPL 2.0, like it was done in some others repository of the zeromq project. For now here's my contribution.
I hope this project or https://gist.github.com/sphaero/f9da6ebb9a7a6f679157 can be relicensed under MPL 2.0, so that we can use it on our GPL 2.0 repository (the licences are compatible. Its not the case with GPL 3.0)
> Fix GetAdaptersAddresses Windows calls + IPv6

- tests/test_network_disconnect.py
Test case for PR #136
Fixes issue #135
> Stopping Pyre blocks after network disconnect test case

- README.md
Updated `README.md` file with the appropriate link.
> Fix broken link in README.md. Fixes #139

- README.md
- examples/chat.py
> Problem: some debug statements were left behind in chat example

- tests/test_network_disconnect.py
@keent Following up on https://github.com/zeromq/pyre/pull/151#issuecomment-852357513: Python 2.7 to 3.5 have all reached their [end of life](https://stackoverflow.com/questions/40655195/is-there-official-guide-for-python-3-x-release-lifecycle). It might be time to consider dropping their support.
All three Python versions fail with a syntax error in `test_network_disconnect.py` (contains type annotations which are only supported in >= 3.6). I remove the incompatible syntax in this PR.
> Restore test syntax compatibility with Python 2.7, 3.4, and 3.5

- .github/workflows/deploy.yml
Fixes https://github.com/zeromq/pyre/pull/159#issuecomment-904494592
> Allow to manually trigger deployment action
