pyre/zsocket.py
ZSocket.signal() makes sure that signal_value is an 8-byte value, and uses struct.pack() to pack this in a 4-byte long. Somehow this works on Linux, but Windows (rightfully?) raises and out-of-range error.
The patch packs the 8-byte signal_value in an 8-byte unsigned long long instead of 4-byte unsigned long.
=> [Regression] ZSocket.signal broken on windows

pyre/pyre_node.py
The STOP message should send the node id as a string of 16 bytes instead of a hex string.
Fixes https://github.com/z25/pyZOCP/issues/57
=> Fix STOP message

examples/chat.py, examples/high_volume.py, pyre/pyre.py, tests/test_pyre.py
Since we have official python bindings for Zyre I'm aiming for Pyre to be a drop in replacement of Zyre in case no Zyre libs are available on a host. Therefore the API needs to be exactly the same. This PR does that.
As Pyre is still in development I've not provided compatibility. Please step forward if you object.
=> Major Pyre API change to equal Zyre api

pyre/zhelper.py
The socket module for Python 2.x in Windows does not have an implementation for inet_ntop. Fortunately a native implementation is available as an external module:
https://pypi.python.org/pypi/win_inet_pton
https://github.com/hickeroar/win_inet_pton
=> Use win_inet_pton for Python 2 on Windows

.gitignore, pyre/zbeacon.py, setup.py
During interface selection, this will prevent zbeacon from choosing a link-local device.  It is useful on a development system with interfaces that are enabled but disconnected, for example virtual or secondary NICs.
=> Skip over link-locals when selecting an interface.

.gitignore, Vagrantfile
fixes #89 
https://www.vagrantup.com/docs/getting-started/
adding a Vagrantfile that helps bootstrap an Ubuntu 14.04 LTS environment with a python virtualenvwrapper environment making testing and develop easier. the Vagrantfile:
+ gets ubuntu up to date
+ installs latest version of python 2.7 via deadsnakes ppa
+ installs required python deps for pyre
+ creates a python virtual env called 'pyre'
+ ties the Virtualbox interface to the public network
goal is to make it easier for developers to test-drive pyre without having to figure out all the underlying deps.
=> adding Vagrantfile to bootstrap sandbox env

README.md
The example chat program in README.md had the following issues:
- Extra indentation of all lines
- Misspelled variable names which prevented the code from running
- Incorrect indentation of some lines
These problems had been fixed by other contributors in the code in examples/chat.py, but README.md was not updated. Thus, I have replaced the outdated example in readme.md with the working version from examples/chat.py
Perhaps README.md should also include a link to that file for convenience?
=> Fixed README.md to match the code in examples/chat.py

pyre/pyre_peer.py, pyre/zre_msg.py
Problem details:
1) `PyrePeer` crashes on malformed `logger.debug` call
2) `ZreMsg` raises `ValueError` if address is malformed
Solution:
1) Fix debug call format
2) try/catch on `UUID` creation, return `None` on failure
Also: Removes some trailing whitespaces.
=> Problem: Pyre crashes

pyre/pyre.py, pyre/pyre_event.py, pyre/pyre_node.py
Solution: Implement "ENDPOINT" command that returns pyre_node.endpoint
=> Problem: Pyre misses access to own endpoint information

pyre/pyre_event.py, pyre/pyre_peer.py, pyre/zbeacon.py
Solutions:
1.  Use `zmq.Again` which is a wrapper for `zmq.EAGAIN`
2. Remove `try/except` in `PyreEvent.__init__`. Let user handle the error explicitly.
=> Problem: Typo in pyre_peer and bad error handling in pyre_event

pyre/pyre.py, tests/test_pyre.py
Solution: Build two `PyreEvent` iterators:
1. `Pyre.recent_events()`: Yields events as long as there are POLLIN events in the inbox
2. `Pyre.events()`: Yields events indefinitely.
=> Problem: Missing PyreEvent iterators

pyre/zre_msg.py
`self`, `key`, and `val`are all undefined names in this context.
=> Comment out line because of undefined names

.travis.yml
__Problems:__
* Python 3.2 is already removed but there are still tests for its presence.
* Python 3.3 goes EOL later this month
* https://docs.python.org/devguide/index.html#branchstatus
__Solution:__
* Remove all mention of Python 3.2 and 3.3 from `.travis.yml`
=> Remove Python 3.2 and 3.3 from testing

pyre/pyre_peer.py, pyre/zre_msg.py
The internal status of `PyrePeer` isn't restricted to the bounds of `number1`, leading to a `struct.error` during otherwise normal operation.
Additionally, `ZreMsg` reads/writes `number1` as a signed byte instead of an unsigned byte as is done in `Zyre`.
=> Fix crash when peer status exceeds 127

pyre/pyre_node.py, pyre/zactor.py
This PR addresses #135 
---
- Implementing beacon reconnect on connection drops. However, it is not clear what the exact behavior should be and how it fits into the overall system. Maybe this PR could fuel further discussions on this topic.
=> Fix stopping Pyre after network disconnect 

pyre/zbeacon.py
Hey guys, This PR is my first ever, so pls forgive me if I violate any conventions :). I started trying out pyre a week ago, but ran into issues when computers entered sleep. I am working on MacOS systems, specifically 10.14.5. I am using the latest pyre master, as of writing this PR - a34ce3e7d0aeb1f2203d79b46a747f8f36b48430 
**PROBLEM**
To reproduce the issue, I simply start a node on two computers both attached to an access point:
`import pyre`
`n = pyre.Pyre()`
`n.join("CHAT")`
`n.start()`
I can see that both computers are sending their zbeacons to the broadcast address which is fine. I then let either one of them go to sleep. Once I wake the sleepy computer up, it no longer sends any beacons to the broadcast address. 
I ran the same setup in debug and noticed that in zbeacon.py, the …
=> Fix compsleep kills zbeacon

pyre/zre_msg.py
Hello,
As said by https://github.com/zeromq/pyzmq/blob/bee745b3e4e5562651c68b0768eda43b4996ba7b/zmq/sugar/socket.py#L113, Socket.socket_type is deprecated. Socket.type should be used instead.
Otherwise it generates many DeprecationWarning.
Cheers,
Axel
=> Socket.socket_type is deprecated for Socket.type

pyre/pyre_node.py
Problem: If a peer with an unknown uuid connects, and there was known peer with the same endpoint, the previous peer is purged silently.
By removing the peer explicitly, the Pyre user receives an EXIT event for the purged peer and which allows the user to properly cleanup any resources bound to the purged peer.
=>  Remove previous peer on duplicated endpoint

.github/workflows/main.yml, setup.py
This PR is an attempt to solve #14
This PR introduces a small Github Action to build a source distribution (`sdist`, using the official `build` module) and uses the official Github Action for deploying it to PyPI.
The Action builds the `sdist` on all pushes and pull requests. (Ideally, this `sdist` would be used for running the tests.) If the `push` event is associated with a `git tag` and the `sdist` build was successful, it will attempt to deploy the `sdist` to PyPI. 
In order for the deployment to work, the maintainers need to set up a repository secret named `PYPI_TOKEN`. You can read more about PyPI API tokens [here](https://pypi.org/help/#apitoken).
After merging, a new tag needs to be created and pushed to initiate the deployment.
As discussed in #14, the `pyre` PyPI project is …
=> Deploy source distribution to PyPI using Github Actions

.github/workflows/deploy.yml, MAINTENANCE.md
To finalize the PyPI-deployment automation started in #155, we need additional permissions to push the version-bumped commit (generated by the github action) back to the repository.
This PR requires setting up a **secret with a personal access token** as described [here](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#granting-additional-permissions). The secrets name should be `PERSONAL_ACCESS_TOKEN`. @bluca is this something you could help us with, again?
=> Github Action: Use personal access token to push bumped version to repo

.github/workflows/bump_version.yml, .github/workflows/deploy.yml, MAINTENANCE.md
Due to security restrictions, pull requests from forked repositories do not
have access to the workflow's secret. As a result, the "Deploy to PyPI" workflow will fail
and not trigger a deployment (see https://github.com/zeromq/pyre/pull/157#issuecomment-862613841).
In these cases, the deployment needs to be triggered again by manually dispatching the workflow.
Unfortunately, I have not found a way to fully automate this process.
To allow for further flexibility, this PR splits the version-bumping from the deployment workflow.
Specifically, this causes the deployment workflow to trigger on all pushed tags, not only those
created by the "Bump version" workflow.
=> Split version-bumping and deployment into separate workflows

pyre/zbeacon.py
Possible workaround for https://github.com/zeromq/pyre/issues/137
=> Gracefully handle issues during zbeacon socket preparations

.github/workflows/deploy.yml, .github/workflows/test.yml
=> updates actions/upload-artifact to v4

pyre/pyre.py, pyre/pyre_node.py, pyre/zbeacon.py, tests/test_zbeacon.py
if selected interface is a single digit, then it is used as an array index in the network interface list
otherwise the selected interface is attempted
otherwise the default behaviour of looping through the network interface list, selecting the first eligible.
this continues the closed pull request here: https://github.com/zeromq/pyre/pull/164
=> implements set_interface
